import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterContext from "@/context/ToastContext";
import AuthContext from "@/context/AuthContext";
import getMovieRandom from "./actions/getMovieRandom";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="vi">
      <body className={inter.className}>
        <AuthContext>

          <ToasterContext />


          {children}
        </AuthContext>
      </body>
    </html>
  );
}
